import type { Neighborhood } from "../schemas/hood.schema";

export type NeighborhoodSeed = Partial<Neighborhood> & { name: string };

/**
 * Centres were checked against OpenStreetMap (Nominatim/Overpass place nodes
 * and landmarks) and reverse-geocode to the named area; they are area
 * centroids, not survey-precise boundaries.
 * radiusMeters approximates each area's footprint, then is trimmed so no two
 * circles overlap (≥100 m apart) — the same rule HoodsService.create enforces.
 */
export const neighborhoodSeeds: NeighborhoodSeed[] = [
  // ── Lagos ─────────────────────────────────────────────────────────────
  {
    name: "Ikeja",
    description: "Commercial and administrative hub of Lagos State",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.348, 6.6] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Ikeja GRA",
    description: "Leafy government reservation area south of Ikeja",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3516, 6.5776] },
    radiusMeters: 800,
    isActive: true,
  },
  {
    name: "Maryland",
    description: "Busy junction district on the Ikorodu Road corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3662, 6.5771] },
    radiusMeters: 700,
    isActive: true,
  },
  {
    name: "Anthony Village",
    description: "Residential district between Maryland and Gbagada",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3723, 6.5638] },
    radiusMeters: 700,
    isActive: true,
  },
  {
    name: "Ogba",
    description: "Residential and light-industrial district north of Ikeja",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.341, 6.6326] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Agege",
    description: "Densely populated trading town on the rail line",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3203, 6.6229] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Ojodu Berger",
    description: "Gateway district at the Lagos–Ibadan Expressway end",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3685, 6.6416] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Magodo",
    description: "Planned residential estate straddling Kosofe and Ikeja",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.38, 6.615] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Ketu",
    description: "Busy transit and market district on Ikorodu Road",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3917, 6.5928] },
    radiusMeters: 800,
    isActive: true,
  },
  {
    name: "Ojota",
    description: "Transit hub district around the Ojota interchange",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3791, 6.5871] },
    radiusMeters: 600,
    isActive: true,
  },
  {
    name: "Ogudu",
    description: "Residential district with Ogudu GRA, beside Gbagada",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3905, 6.575] },
    radiusMeters: 800,
    isActive: true,
  },
  {
    name: "Gbagada",
    description: "Residential district between Yaba and Ketu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.386, 6.556] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Oworonshoki",
    description: "Waterfront community at the Third Mainland Bridge",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4022, 6.5502] },
    radiusMeters: 800,
    isActive: true,
  },
  {
    name: "Bariga",
    description: "Residential district near UNILAG and the lagoon",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.388, 6.5407] },
    radiusMeters: 700,
    isActive: true,
  },
  {
    name: "Somolu",
    description: "Densely populated residential and printing district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3719, 6.5384] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Oshodi",
    description: "Major transport and market hub on the mainland",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.348, 6.5555] },
    radiusMeters: 800,
    isActive: true,
  },
  {
    name: "Mushin",
    description: "Densely populated residential and trading district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3509, 6.5276] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Isolo",
    description: "Residential and industrial district in Oshodi-Isolo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3188, 6.5285] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Ejigbo",
    description: "Residential district east of Ikotun",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2934, 6.5495] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Yaba",
    description: "Tech and education hub, home to UNILAG and YabaTech",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.376, 6.5085] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Surulere",
    description: "Densely populated residential district on the mainland",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.35, 6.496] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Ebute Metta",
    description: "Historic mainland district by the Otto and Iddo rail yards",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3856, 6.4863] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Lagos Island",
    description: "Historic trading core of Lagos around Idumota and Balogun",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3897, 6.4546] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Obalende",
    description: "Transport hub between Lagos Island and Ikoyi",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4061, 6.4491] },
    radiusMeters: 600,
    isActive: true,
  },
  {
    name: "Ikoyi",
    description: "Upscale residential and diplomatic district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4316, 6.4541] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Banana Island",
    description: "Exclusive reclaimed-island estate off Ikoyi",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4529, 6.4642] },
    radiusMeters: 600,
    isActive: true,
  },
  {
    name: "Victoria Island",
    description: "Business and finance district on Lagos Island",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4219, 6.4281] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Lekki Phase 1",
    description: "Residential and commercial estate along the Lekki axis",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4732, 6.4432] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Osapa London",
    description: "Residential area off the Lekki-Epe Expressway",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5083, 6.4445] },
    radiusMeters: 700,
    isActive: true,
  },
  {
    name: "Chevron",
    description: "Residential and office area around the Chevron Drive axis",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5311, 6.4421] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Victoria Garden City",
    description: "Gated residential estate (VGC) on the Lekki-Epe corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5465, 6.464] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Ajah",
    description: "Fast-growing residential suburb on the Lekki-Epe corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.568, 6.4685] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Abraham Adesanya",
    description: "Residential estate area east of Ajah",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5895, 6.4677] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Sangotedo",
    description: "Growing residential district on the Lekki-Epe corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.6356, 6.471] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Badore",
    description: "Residential community north of Ajah along the lagoon",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.616, 6.5099] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Awoyaya",
    description: "Fast-growing residential town in Ibeju-Lekki",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.7046, 6.4697] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Apapa",
    description: "Port and industrial district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3592, 6.4489] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Ajegunle",
    description: "Densely populated community in Ajeromi-Ifelodun",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3335, 6.4482] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Festac Town",
    description: "Planned residential estate in Amuwo-Odofin",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2833, 6.4675] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Satellite Town",
    description: "Residential district along the Badagry Expressway",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2558, 6.4497] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Ojo",
    description: "Residential and university town on the Badagry Expressway",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.1902, 6.4643] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Egbeda",
    description: "Residential district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.289, 6.5912] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Ipaja",
    description: "Residential district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2673, 6.6095] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Iyana Ipaja",
    description: "Busy junction and market district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2973, 6.6173] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Abule Egba",
    description: "Residential and market district on the Lagos–Abeokuta road",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3046, 6.6479] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Ikotun",
    description: "Densely populated residential district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2683, 6.5523] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Igando",
    description: "Residential district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.231, 6.5487] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Ikorodu",
    description: "Large residential and industrial town on the mainland",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5105, 6.6194] },
    radiusMeters: 1800,
    isActive: true,
  },
  {
    name: "Igbogbo",
    description: "Residential town south of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5171, 6.5913] },
    radiusMeters: 1000,
    isActive: true,
  },

  // ── Ibadan ────────────────────────────────────────────────────────────
  {
    name: "Bodija",
    description: "Upscale residential district near the University of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.911, 7.423] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "University of Ibadan",
    description: "Campus community of the University of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8967, 7.4477] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Agbowo",
    description: "Student and residential district opposite UI",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9156, 7.4452] },
    radiusMeters: 600,
    isActive: true,
  },
  {
    name: "Ojoo",
    description: "Northern gateway district on the Ibadan–Oyo road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.915, 7.468] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Apete",
    description: "Residential district near The Polytechnic, Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8722, 7.4492] },
    radiusMeters: 800,
    isActive: true,
  },
  {
    name: "Moniya",
    description: "Fast-growing northern suburb in Akinyele",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9119, 7.5283] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Akobo",
    description: "Residential district off the Lagos–Ibadan Expressway",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.944, 7.432] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Olodo",
    description: "Residential district on the Iwo road axis",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9686, 7.4395] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Alakia",
    description: "Residential district near the Ibadan airport",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9738, 7.3908] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Iwo Road",
    description: "Major commercial and transport hub in Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.933, 7.4035] },
    radiusMeters: 800,
    isActive: true,
  },
  {
    name: "Agodi",
    description: "Government and residential district housing Agodi GRA",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.904, 7.409] },
    radiusMeters: 700,
    isActive: true,
  },
  {
    name: "Mokola",
    description: "Residential and commercial district near Dugbe",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8895, 7.402] },
    radiusMeters: 700,
    isActive: true,
  },
  {
    name: "Eleyele",
    description: "Residential district in the north-west of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8615, 7.41] },
    radiusMeters: 700,
    isActive: true,
  },
  {
    name: "Jericho",
    description: "Reserved residential district (Jericho GRA)",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.867, 7.3955] },
    radiusMeters: 800,
    isActive: true,
  },
  {
    name: "Dugbe",
    description: "Central commercial district of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8795, 7.3878] },
    radiusMeters: 600,
    isActive: true,
  },
  {
    name: "Mapo",
    description: "Historic core of Ibadan around Mapo Hall",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.896, 7.3763] },
    radiusMeters: 600,
    isActive: true,
  },
  {
    name: "Apata",
    description: "Residential and industrial district on the Abeokuta road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.83, 7.381] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Oluyole Estate",
    description: "Residential and industrial estate in south-west Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.858, 7.366] },
    radiusMeters: 800,
    isActive: true,
  },
  {
    name: "Ring Road",
    description: "Commercial district around the Ring Road and Adeoyo",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8725, 7.362] },
    radiusMeters: 700,
    isActive: true,
  },
  {
    name: "Challenge",
    description: "Densely populated residential and commercial district",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.879, 7.3465] },
    radiusMeters: 900,
    isActive: true,
  },
];
