import type { Neighborhood } from "../schemas/hood.schema";

export type NeighborhoodSeed = Partial<Neighborhood> & { name: string };

/**
 * Centres come from OpenStreetMap / geokeo suburb points, GeoNames populated places, or (where
 * neither names the area) a named landmark such as a market, hospital or bus stop in it.
 * radiusMeters is 90% of the distance to the nearest other Hood's centre, capped at the area's
 * own size (3 km at most), so circles overlap but none covers another Hood's centre (the rule
 * HoodsService.create enforces) and findVerifiedMatch splits the shared ground. Together they
 * cover ~91% of built-up Lagos State and ~87% of metro Ibadan (grid cells dense with OSM streets).
 */
export const neighborhoodSeeds: NeighborhoodSeed[] = [
  // ── Lagos ─────────────────────────────────────────────────────────────
  {
    name: "Abijo",
    description: "Residential district on the Lekki-Epe corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.6717, 6.4552] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Aboru",
    description: "Residential district north of Iyana Ipaja",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2821, 6.6245] },
    radiusMeters: 1650,
    isActive: true,
  },
  {
    name: "Abraham Adesanya",
    description: "Residential estate area east of Ajah",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5895, 6.4677] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Abule Ado",
    description: "Residential district off the Badagry Expressway near Festac",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.223, 6.4592] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Abule Egba",
    description: "Residential and market district on the Lagos–Abeokuta road",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3046, 6.6479] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Ado",
    description: "Residential district along Ado–Badore Road",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5828, 6.4959] },
    radiusMeters: 2900,
    isActive: true,
  },
  {
    name: "Agbaku",
    description: "Town north-east of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5833, 6.65] },
    radiusMeters: 2450,
    isActive: true,
  },
  {
    name: "Agbede",
    description: "Residential town north of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4893, 6.6674] },
    radiusMeters: 2450,
    isActive: true,
  },
  {
    name: "Agbowa",
    description: "Town in Epe division",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.7123, 6.6433] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Agege",
    description: "Densely populated trading town on the rail line",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3203, 6.6229] },
    radiusMeters: 1550,
    isActive: true,
  },
  {
    name: "Agidingbi",
    description: "Residential and office district north of Alausa",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3556, 6.6223] },
    radiusMeters: 1750,
    isActive: true,
  },
  {
    name: "Ago Palace",
    description: "Residential district along Ago Palace Way",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.306, 6.503] },
    radiusMeters: 1700,
    isActive: true,
  },
  {
    name: "Agric",
    description: "Residential district around Agric bus stop, Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4839, 6.6254] },
    radiusMeters: 1900,
    isActive: true,
  },
  {
    name: "Agungi",
    description: "Residential district on the Lekki-Epe corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5181, 6.447] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Ajah",
    description: "Fast-growing residential suburb on the Lekki-Epe corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.564, 6.469] },
    radiusMeters: 1700,
    isActive: true,
  },
  {
    name: "Ajao Estate",
    description: "Residential estate by the airport, Isolo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3235, 6.5458] },
    radiusMeters: 1300,
    isActive: true,
  },
  {
    name: "Ajebo",
    description: "Lagoon-side community south of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5306, 6.5336] },
    radiusMeters: 2800,
    isActive: true,
  },
  {
    name: "Ajegunle",
    description: "Densely populated community in Ajeromi-Ifelodun",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3335, 6.4482] },
    radiusMeters: 2250,
    isActive: true,
  },
  {
    name: "Akowonjo",
    description: "Residential and market district between Egbeda and Agege",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3103, 6.6105] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Alagbado",
    description: "Residential district on the Lagos–Abeokuta rail line in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2558, 6.6597] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Alakuko",
    description: "Residential district on the Lagos–Ogun border at Ifako-Ijaiye",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2703, 6.6814] },
    radiusMeters: 2600,
    isActive: true,
  },
  {
    name: "Alasia",
    description: "Community on the Badagry Expressway",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.1374, 6.4949] },
    radiusMeters: 2950,
    isActive: true,
  },
  {
    name: "Amuwo Odofin",
    description: "Residential estate district north of Mile 2",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3116, 6.4782] },
    radiusMeters: 1950,
    isActive: true,
  },
  {
    name: "Anthony Village",
    description: "Residential district between Maryland and Gbagada",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3723, 6.5638] },
    radiusMeters: 950,
    isActive: true,
  },
  {
    name: "Apapa",
    description: "Port and industrial district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3622, 6.4469] },
    radiusMeters: 2050,
    isActive: true,
  },
  {
    name: "Ashipa",
    description: "Residential district between Ayobo and Igando",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2553, 6.5828] },
    radiusMeters: 2200,
    isActive: true,
  },
  {
    name: "Awoyaya",
    description: "Fast-growing residential town in Ibeju-Lekki",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.7046, 6.4697] },
    radiusMeters: 2700,
    isActive: true,
  },
  {
    name: "Ayobo",
    description: "Residential district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2438, 6.602] },
    radiusMeters: 2200,
    isActive: true,
  },
  {
    name: "Badore",
    description: "Residential community north of Ajah along the lagoon",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.616, 6.5099] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Banana Island",
    description: "Exclusive reclaimed-island estate off Ikoyi",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4529, 6.4642] },
    radiusMeters: 900,
    isActive: true,
  },
  {
    name: "Bariga",
    description: "Residential district near UNILAG and the lagoon",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3947, 6.535] },
    radiusMeters: 1600,
    isActive: true,
  },
  {
    name: "Chevron",
    description: "Residential and office area around the Chevron Drive axis",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5311, 6.4421] },
    radiusMeters: 1350,
    isActive: true,
  },
  {
    name: "Command",
    description: "Residential district around Command Road, Ipaja",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2593, 6.6269] },
    radiusMeters: 1900,
    isActive: true,
  },
  {
    name: "Ebute",
    description: "Lagoon-side community west of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4905, 6.6037] },
    radiusMeters: 2250,
    isActive: true,
  },
  {
    name: "Ebute Metta",
    description: "Historic mainland district by the Otto and Iddo rail yards",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3856, 6.4863] },
    radiusMeters: 2150,
    isActive: true,
  },
  {
    name: "Egbeda",
    description: "Residential district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.289, 6.5912] },
    radiusMeters: 1650,
    isActive: true,
  },
  {
    name: "Ejigbo",
    description: "Residential district east of Ikotun",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2934, 6.5495] },
    radiusMeters: 2500,
    isActive: true,
  },
  {
    name: "Elesin",
    description: "Residential district east of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5678, 6.6168] },
    radiusMeters: 2950,
    isActive: true,
  },
  {
    name: "Festac Town",
    description: "Planned residential estate in Amuwo-Odofin",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2833, 6.4675] },
    radiusMeters: 2200,
    isActive: true,
  },
  {
    name: "Gbagada",
    description: "Residential district between Yaba and Ketu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3836, 6.5581] },
    radiusMeters: 1250,
    isActive: true,
  },
  {
    name: "Gbogije",
    description: "Community in Ibeju-Lekki",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.7585, 6.4756] },
    radiusMeters: 2750,
    isActive: true,
  },
  {
    name: "Idimu",
    description: "Residential and market district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2839, 6.5753] },
    radiusMeters: 1650,
    isActive: true,
  },
  {
    name: "Idoluwo",
    description: "Community in Ojo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.1034, 6.4521] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Ifako-Ijaiye",
    description: "Residential district on the Lagos–Abeokuta Expressway",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2895, 6.6636] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Igando",
    description: "Residential district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.231, 6.5487] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Iganmu",
    description: "Industrial district around the National Theatre",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3642, 6.4824] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Igbaga",
    description: "Town north-east of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5828, 6.6748] },
    radiusMeters: 2450,
    isActive: true,
  },
  {
    name: "Igbe",
    description: "Residential town east of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5667, 6.5833] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Igbo Elerin",
    description: "Residential district in Ojo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.1883, 6.4822] },
    radiusMeters: 1800,
    isActive: true,
  },
  {
    name: "Igbobi",
    description: "Residential district around Igbobi, between Fadeyi and Yaba",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3727, 6.5256] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Igbogbo",
    description: "Residential town south of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5171, 6.5913] },
    radiusMeters: 2850,
    isActive: true,
  },
  {
    name: "Ijagemo",
    description: "Residential district off Ijegun–Ijagemo road",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2251, 6.505] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Ijede",
    description: "Lagoon-side town east of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5919, 6.5656] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Ijegun",
    description: "Residential district south of Ikotun",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2549, 6.5162] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Ijesha Tedo",
    description: "Residential district by Coker and Orile",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3334, 6.4882] },
    radiusMeters: 1600,
    isActive: true,
  },
  {
    name: "Ijora",
    description: "Port-side industrial and residential district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3678, 6.4667] },
    radiusMeters: 1600,
    isActive: true,
  },
  {
    name: "Iju",
    description: "Residential district along Iju–Ishaga road",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3247, 6.6507] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Ikeja",
    description: "Commercial and administrative hub of Lagos State",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.348, 6.6] },
    radiusMeters: 1600,
    isActive: true,
  },
  {
    name: "Ikeja GRA",
    description: "Leafy government reservation area south of Ikeja",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3516, 6.5776] },
    radiusMeters: 1300,
    isActive: true,
  },
  {
    name: "Ikogbo",
    description: "Residential district in Ojo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.1919, 6.5059] },
    radiusMeters: 2400,
    isActive: true,
  },
  {
    name: "Ikorodu",
    description: "Large residential and industrial town on the mainland",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5105, 6.6194] },
    radiusMeters: 2500,
    isActive: true,
  },
  {
    name: "Ikota",
    description: "Residential estate area by Ajah",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5683, 6.4521] },
    radiusMeters: 1300,
    isActive: true,
  },
  {
    name: "Ikotun",
    description: "Densely populated residential district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2683, 6.5523] },
    radiusMeters: 2500,
    isActive: true,
  },
  {
    name: "Ikoyi",
    description: "Upscale residential and diplomatic district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4281, 6.4523] },
    radiusMeters: 2200,
    isActive: true,
  },
  {
    name: "Ilasamaja",
    description: "Residential district between Mushin and Isolo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3357, 6.5205] },
    radiusMeters: 1650,
    isActive: true,
  },
  {
    name: "Ilemere",
    description: "Lagoon-side community south-west of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4849, 6.5414] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Ilupeju",
    description: "Industrial and residential estate on the mainland",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3593, 6.5551] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Imota",
    description: "Town in the east of Ikorodu division",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.6694, 6.6636] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Ipaja",
    description: "Residential district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2673, 6.6095] },
    radiusMeters: 1900,
    isActive: true,
  },
  {
    name: "Isasi",
    description: "Residential district in Ojo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.1667, 6.5] },
    radiusMeters: 2550,
    isActive: true,
  },
  {
    name: "Ishawo",
    description: "Residential town north-west of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4644, 6.6661] },
    radiusMeters: 2450,
    isActive: true,
  },
  {
    name: "Isheri Osun",
    description: "Residential district between Okota and Ejigbo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2889, 6.5184] },
    radiusMeters: 2250,
    isActive: true,
  },
  {
    name: "Isiwu",
    description: "Town in the east of Ikorodu division",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.6187, 6.6596] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Isolo",
    description: "Residential and industrial district in Oshodi-Isolo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3188, 6.5285] },
    radiusMeters: 1750,
    isActive: true,
  },
  {
    name: "Iyana Ipaja",
    description: "Busy junction and market district in Alimosho",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2973, 6.6173] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Ketu",
    description: "Busy transit and market district on Ikorodu Road",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3917, 6.5928] },
    radiusMeters: 1350,
    isActive: true,
  },
  {
    name: "Kirikiri",
    description: "Port and industrial district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3114, 6.4426] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Lafiaji",
    description: "Coastal community off Orchid Road, Lekki",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5575, 6.4298] },
    radiusMeters: 2450,
    isActive: true,
  },
  {
    name: "Lagos Island",
    description: "Historic trading core of Lagos around Idumota and Balogun",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3897, 6.4546] },
    radiusMeters: 1700,
    isActive: true,
  },
  {
    name: "Lakowe",
    description: "Residential district on the Lekki-Epe corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.7318, 6.4673] },
    radiusMeters: 2700,
    isActive: true,
  },
  {
    name: "Lekki Phase 1",
    description: "Residential and commercial estate along the Lekki axis",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4874, 6.4423] },
    radiusMeters: 2050,
    isActive: true,
  },
  {
    name: "Madigan",
    description: "Town east of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.6058, 6.6053] },
    radiusMeters: 2650,
    isActive: true,
  },
  {
    name: "Mafoluku",
    description: "Residential district by the airport road, Oshodi",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.332, 6.5596] },
    radiusMeters: 1600,
    isActive: true,
  },
  {
    name: "Magodo",
    description: "Planned residential estate straddling Kosofe and Ikeja",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3778, 6.6181] },
    radiusMeters: 1800,
    isActive: true,
  },
  {
    name: "Majidun",
    description: "Residential district on the Ikorodu Road, west of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4674, 6.6151] },
    radiusMeters: 1900,
    isActive: true,
  },
  {
    name: "Maryland",
    description: "Busy junction district on the Ikorodu Road corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3699, 6.5732] },
    radiusMeters: 950,
    isActive: true,
  },
  {
    name: "Meiran",
    description: "Residential district north of Abule Egba",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.276, 6.656] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Mile 2",
    description: "Transport hub on the Badagry Expressway",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3134, 6.4588] },
    radiusMeters: 1600,
    isActive: true,
  },
  {
    name: "Morekete",
    description: "Residential district south of Igbogbo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5309, 6.5617] },
    radiusMeters: 2800,
    isActive: true,
  },
  {
    name: "Mushin",
    description: "Densely populated residential and trading district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3509, 6.5276] },
    radiusMeters: 1650,
    isActive: true,
  },
  {
    name: "Obalende",
    description: "Transport hub between Lagos Island and Ikoyi",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4061, 6.4491] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Odogunyan",
    description: "Residential district on the Ikorodu–Sagamu road",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5205, 6.6584] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Ogba",
    description: "Residential and light-industrial district north of Ikeja",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.341, 6.6326] },
    radiusMeters: 1750,
    isActive: true,
  },
  {
    name: "Ogombo",
    description: "Residential district off Ogombo Road, Sangotedo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.6137, 6.4503] },
    radiusMeters: 2950,
    isActive: true,
  },
  {
    name: "Ogudu",
    description: "Residential district with Ogudu GRA, beside Gbagada",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3905, 6.575] },
    radiusMeters: 1650,
    isActive: true,
  },
  {
    name: "Ojo",
    description: "Residential and university town on the Badagry Expressway",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.1902, 6.4643] },
    radiusMeters: 1800,
    isActive: true,
  },
  {
    name: "Ojodu Berger",
    description: "Gateway district at the Lagos–Ibadan Expressway end",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3685, 6.6416] },
    radiusMeters: 2300,
    isActive: true,
  },
  {
    name: "Ojota",
    description: "Transit hub district around the Ojota interchange",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3791, 6.5871] },
    radiusMeters: 1350,
    isActive: true,
  },
  {
    name: "Oke Agba",
    description: "Town east of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.65, 6.6] },
    radiusMeters: 2800,
    isActive: true,
  },
  {
    name: "Oke Oloku",
    description: "Town east of Ijede",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.6252, 6.5865] },
    radiusMeters: 2650,
    isActive: true,
  },
  {
    name: "Okota",
    description: "Residential district along Okota Road, Isolo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3215, 6.511] },
    radiusMeters: 1700,
    isActive: true,
  },
  {
    name: "Okun-Ajah",
    description: "Coastal community south of Ajah",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5927, 6.4271] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Ologolo",
    description: "Residential district off Ologolo Road, Lekki",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5175, 6.4317] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Oniru",
    description: "Waterfront estate between Victoria Island and Lekki",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4551, 6.4289] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Opebi",
    description: "Commercial and residential district off Allen Avenue",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3619, 6.5893] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Oregun",
    description: "Commercial and light-industrial district east of Ikeja",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3645, 6.601] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Orile Iganmu",
    description: "Residential and market district near Orile",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3458, 6.4773] },
    radiusMeters: 1600,
    isActive: true,
  },
  {
    name: "Osapa London",
    description: "Residential area off the Lekki-Epe Expressway",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5083, 6.4445] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Oshodi",
    description: "Major transport and market hub on the mainland",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3494, 6.557] },
    radiusMeters: 1000,
    isActive: true,
  },
  {
    name: "Owode Onirin",
    description: "Market district by Mile 12 and the Ikorodu road",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4149, 6.6085] },
    radiusMeters: 2750,
    isActive: true,
  },
  {
    name: "Oworonshoki",
    description: "Waterfront community at the Third Mainland Bridge",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4022, 6.5502] },
    radiusMeters: 1650,
    isActive: true,
  },
  {
    name: "Parafa",
    description: "Residential district north-east of Ikorodu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5477, 6.6389] },
    radiusMeters: 2950,
    isActive: true,
  },
  {
    name: "Sangotedo",
    description: "Growing residential district on the Lekki-Epe corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.6356, 6.471] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Satellite Town",
    description: "Residential district along the Badagry Expressway",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2558, 6.4497] },
    radiusMeters: 1950,
    isActive: true,
  },
  {
    name: "Shasha",
    description: "Busy residential and market district between Egbeda and Akowonjo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3045, 6.585] },
    radiusMeters: 1650,
    isActive: true,
  },
  {
    name: "Shibiri",
    description: "Residential district in Ojo",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.1495, 6.4612] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Somolu",
    description: "Densely populated residential and printing district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.379, 6.5392] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Surulere",
    description: "Densely populated residential district on the mainland",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.359, 6.5025] },
    radiusMeters: 1650,
    isActive: true,
  },
  {
    name: "Trade Fair",
    description: "Trade and residential area around the Trade Fair Complex",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2536, 6.4693] },
    radiusMeters: 1300,
    isActive: true,
  },
  {
    name: "Victoria Garden City",
    description: "Gated residential estate (VGC) on the Lekki-Epe corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5465, 6.464] },
    radiusMeters: 1100,
    isActive: true,
  },
  {
    name: "Victoria Island",
    description: "Business and finance district on Lagos Island",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.426, 6.43] },
    radiusMeters: 2200,
    isActive: true,
  },
  {
    name: "Yaba",
    description: "Tech and education hub, home to UNILAG and YabaTech",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3755, 6.5068] },
    radiusMeters: 1650,
    isActive: true,
  },

  // ── Ibadan ────────────────────────────────────────────────────────────
  {
    name: "Adegbayi",
    description: "Residential district on the Ibadan–Ife road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9866, 7.3834] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Agbada",
    description: "Residential district in Oluyole LGA, west of the Akala Expressway",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.7891, 7.3454] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Agbowo",
    description: "Student and residential district opposite UI",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9156, 7.4452] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Agodi",
    description: "Government and residential district housing Agodi GRA",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.904, 7.409] },
    radiusMeters: 1200,
    isActive: true,
  },
  {
    name: "Agugu",
    description: "Densely populated residential district in Ibadan North East",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.925, 7.3845] },
    radiusMeters: 1350,
    isActive: true,
  },
  {
    name: "Ajibode",
    description: "Residential district bordering the University of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8923, 7.4621] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Akingbile",
    description: "Residential district on the Moniya road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9115, 7.5135] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Akobo",
    description: "Residential district off the Lagos–Ibadan Expressway",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.944, 7.432] },
    radiusMeters: 2050,
    isActive: true,
  },
  {
    name: "Alakia",
    description: "Residential district near the Ibadan airport",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9738, 7.3908] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Alalubosa",
    description: "Reserved residential district (Alalubosa GRA)",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8617, 7.3839] },
    radiusMeters: 1100,
    isActive: true,
  },
  {
    name: "Alaro",
    description: "Residential district in Ona Ara LGA, east of Amuloko",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [4.0093, 7.3574] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Amuloko",
    description: "Fast-growing residential district in Ona Ara",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9759, 7.3366] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Apata",
    description: "Residential and industrial district on the Abeokuta road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.83, 7.381] },
    radiusMeters: 2100,
    isActive: true,
  },
  {
    name: "Apete",
    description: "Residential district near The Polytechnic, Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8722, 7.4492] },
    radiusMeters: 1150,
    isActive: true,
  },
  {
    name: "Ashi",
    description: "Residential district between Bodija and Akobo",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9229, 7.4317] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Awotan",
    description: "Residential district beside Apete",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8618, 7.4435] },
    radiusMeters: 1150,
    isActive: true,
  },
  {
    name: "Basorun",
    description: "Residential district north of Iwo Road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.932, 7.415] },
    radiusMeters: 1150,
    isActive: true,
  },
  {
    name: "Bode-Igbo",
    description: "Residential district in Ido LGA on Ibadan's western edge",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.789, 7.3962] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Bodija",
    description: "Upscale residential district near the University of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.911, 7.423] },
    radiusMeters: 1150,
    isActive: true,
  },
  {
    name: "Challenge",
    description: "Densely populated residential and commercial district",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.879, 7.3465] },
    radiusMeters: 1300,
    isActive: true,
  },
  {
    name: "Dugbe",
    description: "Central commercial district of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8795, 7.3878] },
    radiusMeters: 950,
    isActive: true,
  },
  {
    name: "Elebu",
    description: "Residential district off the Akala Expressway",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8333, 7.3559] },
    radiusMeters: 2050,
    isActive: true,
  },
  {
    name: "Elegun",
    description: "Residential district in Oluyole LGA, south-east Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.931, 7.3165] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Eleyele",
    description: "Residential district in the north-west of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8615, 7.41] },
    radiusMeters: 1550,
    isActive: true,
  },
  {
    name: "Faruku",
    description: "Residential district in Oluyole LGA, south of Odo Ona",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8871, 7.2836] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Felele",
    description: "Residential district south of Challenge",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.886, 7.335] },
    radiusMeters: 1300,
    isActive: true,
  },
  {
    name: "Gate",
    description: "Busy market and transport district at Agodi Gate",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.921, 7.3976] },
    radiusMeters: 1300,
    isActive: true,
  },
  {
    name: "Gbagi",
    description: "Market district on the Old Ife road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9559, 7.3934] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Idioro",
    description: "Residential district in Ido LGA, north-west of Eleyele",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8267, 7.4358] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Ijokodo",
    description: "Residential district along Ijokodo Road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.881, 7.43] },
    radiusMeters: 1900,
    isActive: true,
  },
  {
    name: "Iletitun",
    description: "Residential district in Egbeda LGA, off the Ife road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [4.0099, 7.4011] },
    radiusMeters: 2900,
    isActive: true,
  },
  {
    name: "Iwo Road",
    description: "Major commercial and transport hub in Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.933, 7.4035] },
    radiusMeters: 1150,
    isActive: true,
  },
  {
    name: "Jericho",
    description: "Reserved residential district (Jericho GRA)",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8648, 7.3948] },
    radiusMeters: 1100,
    isActive: true,
  },
  {
    name: "Kasela",
    description: "Residential district in Akinyele LGA, north-east of Ojoo",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9555, 7.4758] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Kuola",
    description: "Residential district on the Akala Expressway",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8149, 7.3661] },
    radiusMeters: 2050,
    isActive: true,
  },
  {
    name: "Mapo",
    description: "Historic core of Ibadan around Mapo Hall",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.896, 7.3763] },
    radiusMeters: 1400,
    isActive: true,
  },
  {
    name: "Mokola",
    description: "Residential and commercial district near Dugbe",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8895, 7.402] },
    radiusMeters: 1300,
    isActive: true,
  },
  {
    name: "Molete",
    description: "Residential and commercial district on the Lagos bypass",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.888, 7.358] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Moniya",
    description: "Fast-growing northern suburb in Akinyele",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9119, 7.5283] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Odinjo",
    description: "Densely populated residential district in Ibadan South East",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.913, 7.3591] },
    radiusMeters: 2400,
    isActive: true,
  },
  {
    name: "Odo Ona",
    description: "Residential district south of Oluyole Estate",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8593, 7.3373] },
    radiusMeters: 2150,
    isActive: true,
  },
  {
    name: "Ojoo",
    description: "Northern gateway district on the Ibadan–Oyo road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.915, 7.468] },
    radiusMeters: 1700,
    isActive: true,
  },
  {
    name: "Oke Ado",
    description: "Busy residential and commercial district south of Dugbe",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8797, 7.3781] },
    radiusMeters: 950,
    isActive: true,
  },
  {
    name: "Olode",
    description: "Residential district on the Iwo road axis",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9828, 7.4155] },
    radiusMeters: 2600,
    isActive: true,
  },
  {
    name: "Olodo",
    description: "Residential district on the Iwo road axis",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9686, 7.4395] },
    radiusMeters: 2550,
    isActive: true,
  },
  {
    name: "Olokofefe",
    description: "Residential district in Oluyole LGA, south-west Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8365, 7.3076] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Olude",
    description: "Residential district in Ido LGA, north-west Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8389, 7.4826] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Olunloyo",
    description: "Residential district along Akanran Road in Ona Ara",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.948, 7.3491] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Oluyole Estate",
    description: "Residential and industrial estate in south-west Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.858, 7.366] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Podo",
    description: "Industrial and residential district by the Lagos–Ibadan Expressway (Odo Ona axis)",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8692, 7.3154] },
    radiusMeters: 2400,
    isActive: true,
  },
  {
    name: "Ring Road",
    description: "Commercial district around the Ring Road and Adeoyo",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8725, 7.362] },
    radiusMeters: 1450,
    isActive: true,
  },
  {
    name: "Sango",
    description: "Residential and commercial district on the Oyo road",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8991, 7.4239] },
    radiusMeters: 1150,
    isActive: true,
  },
  {
    name: "Sasa",
    description: "Residential and market district north of Ojoo",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9144, 7.485] },
    radiusMeters: 1700,
    isActive: true,
  },
  {
    name: "Temidire",
    description: "Residential district in Ona Ara LGA, south-east Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9671, 7.3067] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "University of Ibadan",
    description: "Campus community of the University of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8967, 7.4477] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Yemetu",
    description: "Densely populated residential district east of Mokola",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9047, 7.3875] },
    radiusMeters: 1400,
    isActive: true,
  },
];
