import { Neighborhood } from "../schemas/neighborhood.schema";

export type NeighborhoodSeed = Partial<Neighborhood> & { name: string };

/**
 * Coordinates are approximate area centroids (dev/seed-grade, not
 * survey-precise) — good enough to exercise proximity matching locally, but
 * verify/refine via a geocoder before relying on them in production.
 * radiusMeters is a rough guess at each area's footprint: tighter for small,
 * dense districts, wider for sprawling ones.
 */
export const neighborhoodSeeds: NeighborhoodSeed[] = [
  // ── Lagos ──────────────────────────────────────────────────────────────
  {
    name: "Ikeja",
    description: "Commercial and administrative hub of Lagos State",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3515, 6.6018] },
    radiusMeters: 3000,
    isActive: true,
  },
  {
    name: "Victoria Island",
    description: "Business and finance district on Lagos Island",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4219, 6.4281] },
    radiusMeters: 2500,
    isActive: true,
  },
  {
    name: "Ikoyi",
    description: "Upscale residential and diplomatic district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4316, 6.4541] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Lekki Phase 1",
    description: "Residential and commercial estate along the Lekki axis",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.4732, 6.4432] },
    radiusMeters: 2500,
    isActive: true,
  },
  {
    name: "Ajah",
    description: "Fast-growing residential suburb on the Lekki-Epe corridor",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5852, 6.4698] },
    radiusMeters: 3500,
    isActive: true,
  },
  {
    name: "Yaba",
    description: "Tech and education hub, home to UNILAG and YabaTech",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3711, 6.5095] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Surulere",
    description: "Densely populated residential district on the mainland",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.354, 6.5027] },
    radiusMeters: 2500,
    isActive: true,
  },
  {
    name: "Gbagada",
    description: "Residential district between Yaba and Ketu",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3889, 6.55] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Magodo",
    description: "Planned residential estate straddling Kosofe and Ikeja",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3789, 6.6135] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Apapa",
    description: "Port and industrial district",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.3592, 6.4489] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Festac Town",
    description: "Planned residential estate in Amuwo-Odofin",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.2833, 6.4675] },
    radiusMeters: 2500,
    isActive: true,
  },
  {
    name: "Ikorodu",
    description: "Large residential and industrial town on the mainland",
    city: "Lagos",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.5105, 6.6194] },
    radiusMeters: 4000,
    isActive: true,
  },

  // ── Ibadan ─────────────────────────────────────────────────────────────
  {
    name: "Bodija",
    description: "Upscale residential district near the University of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9017, 7.4306] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Dugbe",
    description: "Central commercial district of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8967, 7.3775] },
    radiusMeters: 1800,
    isActive: true,
  },
  {
    name: "Mokola",
    description: "Residential and commercial district near Dugbe",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9022, 7.3958] },
    radiusMeters: 1500,
    isActive: true,
  },
  {
    name: "Agodi",
    description: "Government and residential district housing Agodi GRA",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9083, 7.4056] },
    radiusMeters: 1800,
    isActive: true,
  },
  {
    name: "Jericho",
    description: "Reserved residential district (Jericho GRA)",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8814, 7.3903] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Challenge",
    description: "Densely populated residential and commercial district",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.885, 7.355] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Iwo Road",
    description: "Major commercial and transport hub in Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.9333, 7.4022] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Eleyele",
    description: "Residential district in the north-west of Ibadan",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8631, 7.4028] },
    radiusMeters: 2000,
    isActive: true,
  },
  {
    name: "Apata",
    description: "Residential and industrial district south-west of Dugbe",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8556, 7.3444] },
    radiusMeters: 2500,
    isActive: true,
  },
  {
    name: "Ring Road",
    description: "Commercial district around the Ring Road roundabout",
    city: "Ibadan",
    country: "Nigeria",
    location: { type: "Point", coordinates: [3.8917, 7.3733] },
    radiusMeters: 1500,
    isActive: true,
  },
];
