/**
 * Central catalogue of the marketing imagery used across the landing pages.
 *
 * Every entry points at a SELF-HOSTED copy under /public/images (generated by
 * `node apps/web/scripts/fetch-images.mjs`), with its attribution metadata kept
 * alongside so we stay compliant with the source licences (Wikimedia CC BY-SA
 * and Unsplash).
 *
 * ── How to switch images ────────────────────────────────────────────────────
 * The active image is `HERO_IMAGE` / `TRUST_IMAGE`. They are set to the first
 * entry of their array. To try a different candidate, change the index:
 *
 *     export const HERO_IMAGE  = HERO_IMAGES[1];  // switch to the Mile 12 market
 *     export const TRUST_IMAGE = TRUST_IMAGES[2]; // switch to "neighbors on a bench"
 *
 * All candidates are already downloaded locally, so switching is instant and
 * keeps the site free of external image dependencies.
 */

export interface SiteImage {
  /** Local path under /public (self-hosted, WebP). */
  src: string;
  alt: string;
  /** Human-readable name for docs / pickers. */
  label: string;
  /** Attribution text shown under the image. */
  credit: string;
  /** Link to the photographer / source page. */
  creditUrl: string;
  /** object-position focal point for object-cover crops (defaults to center). */
  position?: string;
  /** Device-specific framing for narrow (mobile) screens. */
  mobile?: {
    /** Tailwind aspect-ratio utility for the mobile container, e.g. "16/10". */
    aspectRatio?: string;
    /** Focal-point override for the mobile crop. */
    position?: string;
  };
}

/** Landing-page hero background. Order = preference. */
export const HERO_IMAGES: SiteImage[] = [
  {
    src: "/images/hero-street.webp",
    alt: "A busy Lagos street filled with traffic and commuters",
    label: "Busy Lagos street",
    credit: "Opeyemi Adisa",
    creditUrl: "https://unsplash.com/@niceyem",
    position: "50% 45%",
    mobile: { aspectRatio: "16/9", position: "50% 45%" },
  },
  {
    src: "/images/hero-market.webp",
    alt: "A busy market street in Mile 12, Lagos, Nigeria",
    label: "Mile 12 market (current)",
    credit: "A Busy Market in Mile 12 (CC BY-SA 4.0)",
    creditUrl:
      "https://commons.wikimedia.org/wiki/File:A_Busy_Market_in_Mile_12,_Lagos-_Nigeria.jpg",
  },
  {
    src: "/images/hero-aerial.webp",
    alt: "Aerial view of Lagos city buildings",
    label: "Lagos aerial",
    credit: "Nupo Deyon Daniel",
    creditUrl: "https://unsplash.com/@thewallpaperguy_",
  },
  {
    src: "/images/hero-skyline.webp",
    alt: "Lagos city skyline during the daytime",
    label: "City skyline",
    credit: "Stephen Olatunde",
    creditUrl: "https://unsplash.com/@targetfotografi",
  },
  {
    src: "/images/hero-traffic.webp",
    alt: "Vehicles on a Lagos roadway during the daytime",
    label: "Road traffic",
    credit: "Zenith Wogwugwu",
    creditUrl: "https://unsplash.com/@zenithy",
  },
];

/** Trust & safety section image. Order = preference. */
export const TRUST_IMAGES: SiteImage[] = [
  {
    src: "/images/trust-hands.webp",
    alt: "Two women holding hands in a show of trust and connection",
    label: "Holding hands",
    credit: "John McArthur",
    creditUrl: "https://unsplash.com/@snowjam",
  },
  {
    src: "/images/trust-current.webp",
    alt: "A smiling market woman at the Monday Market in Kakuri, Kaduna, Nigeria",
    label: "Smiling market woman",
    credit: "Kambai Akau (CC BY-SA 4.0)",
    creditUrl:
      "https://commons.wikimedia.org/wiki/File:A_smiling_market_woman_at_the_Monday_Market_in_Kakuri,_Kaduna_02.jpg",
  },
  {
    src: "/images/trust-neighbors.webp",
    alt: "Women in colorful clothes sitting together on a bench outdoors",
    label: "Neighbors on a bench (current)",
    credit: "Random Institute",
    creditUrl: "https://unsplash.com/@randominstitute",
  },
  {
    src: "/images/trust-community.webp",
    alt: "Three women carrying basins while walking together",
    label: "Community together",
    credit: "Ninno JackJr",
    creditUrl: "https://unsplash.com/@ninnojackjr",
  },
  {
    src: "/images/trust-smile.webp",
    alt: "A smiling woman wearing a turban",
    label: "Warm smile",
    credit: "Prince Akachi",
    creditUrl: "https://unsplash.com/@princearkman",
  },
];

/** About / how-it-works hero — the previously ~2.3 MB aerial, now compressed. */
export const ABOUT_AERIAL: SiteImage = {
  src: "/images/about-aerial.webp",
  alt: "Aerial view of Lagos Island, Nigeria",
  label: "Lagos Island aerial",
  credit: "Ei'eke (CC BY-SA 4.0)",
  creditUrl:
    "https://commons.wikimedia.org/wiki/File:Aerial_view_of_Lagos_Island.jpg",
};

/** Safe indexed access so the active image is always typed as defined. */
function at<T>(list: T[], index: number): T {
  const item = list[index] ?? list[0];
  if (!item) throw new Error("Image list must not be empty.");
  return item;
}

/** Active image for each slot — change the index to pick a different one. */
export const HERO_IMAGE = at(HERO_IMAGES, 0);
export const TRUST_IMAGE = at(TRUST_IMAGES, 2);
